apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"jenkins"},"name":"jenkins-deployment","namespace":"monitoring"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"jenkins"}},"template":{"metadata":{"labels":{"app":"jenkins"}},"spec":{"containers":[{"image":"jenkins/jenkins","name":"jenkins","ports":[{"containerPort":8080}],"volumeMounts":[{"mountPath":"/var/jenkins_home","name":"nfs-volume"}]}],"volumes":[{"name":"nfs-volume","nfs":{"path":"/volume1/linux-tools/docker/jenkins","server":"10.10.0.217"}}]}}}}
  creationTimestamp: "2019-08-04T19:03:04Z"
  generation: 1
  labels:
    app: jenkins
  name: jenkins-deployment
  namespace: monitoring
  resourceVersion: "5923645"
  selfLink: /apis/extensions/v1beta1/namespaces/monitoring/deployments/jenkins-deployment
  uid: 05144793-a1c4-4ab7-a3da-87152e62d8e0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: nfs-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-volume
        nfs:
          path: /volume1/linux-tools/docker/jenkins
          server: 10.10.0.217
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-08-04T19:03:04Z"
    lastUpdateTime: "2019-08-04T19:03:12Z"
    message: ReplicaSet "jenkins-deployment-7db98bc947" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-08-06T05:11:41Z"
    lastUpdateTime: "2019-08-06T05:11:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
