apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-08-05T23:32:23Z"
  generation: 1
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.6
    heritage: Tiller
    release: nfs-client-provisioner-standard
  name: nfs-client-provisioner-standard
  namespace: monitoring
  resourceVersion: "5869045"
  selfLink: /apis/extensions/v1beta1/namespaces/monitoring/deployments/nfs-client-provisioner-standard
  uid: 97118ad6-4687-45ab-b46f-33210041f5ae
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-client-provisioner
      release: nfs-client-provisioner-standard
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-client-provisioner
        release: nfs-client-provisioner-standard
    spec:
      containers:
      - env:
        - name: PROVISIONER_NAME
          value: cluster.local/nfs-client-provisioner-standard
        - name: NFS_SERVER
          value: 10.10.0.217
        - name: NFS_PATH
          value: /volume1/k8s-vol
        image: quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
        imagePullPolicy: IfNotPresent
        name: nfs-client-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persistentvolumes
          name: nfs-client-root
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-client-provisioner-standard
      serviceAccountName: nfs-client-provisioner-standard
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-client-root
        nfs:
          path: /volume1/k8s-vol
          server: 10.10.0.217
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-08-05T23:32:27Z"
    lastUpdateTime: "2019-08-05T23:32:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-08-05T23:32:23Z"
    lastUpdateTime: "2019-08-05T23:32:27Z"
    message: ReplicaSet "nfs-client-provisioner-standard-6984cf6984" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
