apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"couchpotato"},"name":"couchpotato-deployment","namespace":"mark-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"couchpotato"}},"template":{"metadata":{"labels":{"app":"couchpotato"}},"spec":{"containers":[{"image":"linuxserver/couchpotato","name":"couchpotato","ports":[{"containerPort":5050}],"volumeMounts":[{"mountPath":"/config","name":"nfs-volume-couchpotato"},{"mountPath":"/mnt/sabnzb","name":"nfs-volume-downloads"}]}],"volumes":[{"name":"nfs-volume-couchpotato","nfs":{"path":"/volume1/linux-tools/docker/couchpotato","server":"10.10.0.217"}},{"name":"nfs-volume-downloads","nfs":{"path":"/volume1/sabnzb","server":"10.10.0.217"}}]}}}}
  creationTimestamp: "2019-06-30T11:08:26Z"
  generation: 13
  labels:
    app: couchpotato
  name: couchpotato-deployment
  namespace: mark-ns
  resourceVersion: "4815578"
  selfLink: /apis/extensions/v1beta1/namespaces/mark-ns/deployments/couchpotato-deployment
  uid: b6d6dabb-337b-417a-8c02-1f4a6145bbde
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: couchpotato
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchpotato
    spec:
      containers:
      - image: linuxserver/couchpotato
        imagePullPolicy: Always
        name: couchpotato
        ports:
        - containerPort: 5050
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: nfs-volume-couchpotato
        - mountPath: /mnt/sabnzb
          name: nfs-volume-downloads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-volume-couchpotato
        nfs:
          path: /volume1/linux-tools/docker/couchpotato
          server: 10.10.0.217
      - name: nfs-volume-downloads
        nfs:
          path: /volume1/sabnzb
          server: 10.10.0.217
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-30T11:08:26Z"
    lastUpdateTime: "2019-06-30T11:08:47Z"
    message: ReplicaSet "couchpotato-deployment-84687c4c4d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-07-31T02:29:06Z"
    lastUpdateTime: "2019-07-31T02:29:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 13
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
