apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nzbget"},"name":"nzbget-deployment","namespace":"mark-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nzbget"}},"template":{"metadata":{"labels":{"app":"nzbget"}},"spec":{"containers":[{"image":"linuxserver/nzbget","name":"nzbget","ports":[{"containerPort":6789}],"volumeMounts":[{"mountPath":"/config","name":"nfs-volume-nzbget"},{"mountPath":"/downloads","name":"nfs-volume-downloads"}]}],"volumes":[{"name":"nfs-volume-nzbget","nfs":{"path":"/volume1/linux-tools/docker/nzbget/appdata","server":"10.10.0.217"}},{"name":"nfs-volume-downloads","nfs":{"path":"/volume1/linux-tools/docker/nzbget/downloads","server":"10.10.0.217"}}]}}}}
  creationTimestamp: "2019-06-30T11:43:44Z"
  generation: 14
  labels:
    app: nzbget
  name: nzbget-deployment
  namespace: mark-ns
  resourceVersion: "5506112"
  selfLink: /apis/extensions/v1beta1/namespaces/mark-ns/deployments/nzbget-deployment
  uid: 92c57fc9-a384-46ae-9215-19c700519f15
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nzbget
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nzbget
    spec:
      containers:
      - image: linuxserver/nzbget
        imagePullPolicy: Always
        name: nzbget
        ports:
        - containerPort: 6789
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: nfs-volume-nzbget
        - mountPath: /downloads
          name: nfs-volume-downloads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-volume-nzbget
        nfs:
          path: /volume1/linux-tools/docker/nzbget/appdata
          server: 10.10.0.217
      - name: nfs-volume-downloads
        nfs:
          path: /volume1/linux-tools/docker/nzbget/downloads
          server: 10.10.0.217
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-30T11:43:44Z"
    lastUpdateTime: "2019-06-30T11:44:06Z"
    message: ReplicaSet "nzbget-deployment-67457cd5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-08-04T01:42:45Z"
    lastUpdateTime: "2019-08-04T01:42:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
