apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2019-06-29T11:17:23Z"
  name: kube-public
  resourceVersion: "5"
  selfLink: /api/v1/namespaces/kube-public
  uid: 0fd41f44-3697-43d3-9c30-ec4bea38d33d
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
