apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"env":"dev"},"name":"the-project"}}
  creationTimestamp: "2019-08-05T23:13:50Z"
  labels:
    env: dev
  name: the-project
  resourceVersion: "5866344"
  selfLink: /api/v1/namespaces/the-project
  uid: 794d383b-4757-4da6-ab6e-94703dc78d81
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
